name: Publish release artifacts

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra:  ["10.0", "10.0.1", "10.0.2", "10.0.3"]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
          java-package: jdk
          architecture: x64
      - uses: er28-0652/setup-ghidra@master
        with:
          version: ${{ matrix.ghidra }}
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.9
          arguments: test -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.9
          arguments: buildExtension -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}
      - uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*ghidra-emotionengine.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
